server.port=8080

# Application name
spring.application.name=tti-group-backend

# Enable CORS
spring.mvc.cors.allowed-origins=*

# JSON properties
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd
